# Site settings
title: 'Project 58' # Your Title
tagline: 'Madness madness I tell you!' # A brief tagline for your site
sidebar_image: http://www.meh.ro/wp-content/uploads/2014/12/meh.ro11837.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: ""
