# Site settings
title: 'Bonta Vlad blabber space' # Your Title
tagline: 'Madness madness I tell you!' # A brief tagline for your site
sidebar_image: "/images/cover.jpg"

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: ""
