#+STARTUP: showall
#+OPTIONS: toc:nil -:nil
---
layout: post
title: A reader lives a thousand lives
comments: true
categories: jrnl
---

#+BEGIN_QUOTE
 “A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.” - George R.R. Martin, A Dance with Dragons 
#+END_QUOTE
 
---

#+CAPTION: Alice in wonderland
#+NAME:   Alice in wonderland
https://i.imgur.com/VRpST3a.jpg

* A journey of a thousand miles

People read for different reasons, some read to travel, some to feel, some to forget, others read to love, others to hate, most of us read because we have to, everybody reads, nobody escapes!

#+BEGIN_QUOTE
"Each day acquire something that will fortify you against poverty, against death, indeed against other misfortunes as well; and after you have run over many thoughts, select one to be thoroughly digested that day." - *Seneca, Lucius Annaeus*
#+END_QUOTE

So *why* then, reading is harder than ever?

Why do I keep buying books, despite the fact that the pile of unread ones gets bigger and bigger? It grows and leans, ready to fall!

Why do I let myself be frustrated by the feeling of being so close to so many answers, all at my fingertips, yet here I am browsing YouTube /learning/ how to [restore old matchbox cars](https://www.youtube.com/watch?v=Dq6ijqPjc_s) or [how to cook on a wok](https://www.youtube.com/watch?v=Bkvqjaar6x0). And you to Reddit, I hate you, you fucking black hole of time.

Why not simply *read*? Why not open the fucking book and start reading words, words that add up to pages, pages that form chapters, chapters that make up a book. /A journey of a thousand miles begins with a single step/, a step that I take with great effort.

But why? I love reading, reading is something that I enjoy!

* Beware yourself, for you are like the rest
  
But even if I start I don't finish, when I finish I don't remember, when I remember, maybe I don't understand. That is a frightening thought, to invest so much and gain so little.

#+BEGIN_QUOTE
"The primary indication, to my thinking, of a well-ordered mind is a man’s ability to remain in one place and linger in his own company." - *Seneca, Lucius Annaeus*
#+END_QUOTE

The ability to remain in one place, to do something undisturbed, to concentrate on one thing, the thing you are doing, seems like an impossible task. Either it's the phone, or Facebook, or to much coffee, or none, everything want's your attention, there's a big war over it with a lot of money involved. We are taught to want everything, the best, in an instant.

But reading is slow and requires effort, it requires you to /linger in your own company/, not an easy task for most of us, to form ideas, come up with explanations. It requires something from yourself!

So then reading trails behind, books pile up, frustrated journal posts get written!

* Make the best of what is in our power - Epictetus
  
We have to much time on our hands, focus is what we lack. This is my planned that helped me solve that.

If you read only 30 page an hour, you could read a 400 page book in about 13 hours. If you dedicate just 30 minutes each day to reading you could finish that book in a month.

With practice you get faster, thirty pages an hour become sixty, one book a month become two, twelve book a year become many more, more than you initially tought.

In /The Power of Habit: Why We Do What We Do in Life and Business/ Charles Duhigg talks about how old habits never die, only replaced. You have to recognize the habit, find the trigger and the reward. The trigger and the reward are hard things to change, but the habit, that's something we can work with. 

Once you recognize the trigger, quickly switch the habit with something you actually want to do, like reading, but keep the reward the same. By being consistent you retrain the brain to do useful things instead.

After work, to relax, I start browsing YouTube, but instead of watching crap, I put some music and read! I have the same trigger, the habit is different. The reward could be anything, the fuzzy felling I did not waste time, not feeling guilty of actually watching crap on YouTube afterwards, a beer.

Last year I bought a *Kobo Aura One*, a e-book reader similar with Kindle Paper White. Installed some [custom firmware](https://github.com/koreader/koreader), did some configuration and everything was set.

I carry my e-book reader everywhere, you never know when you have to wait for something or someone, and instead of checking Facebook, news.ycombinator or reddit, read! Get those thirty minutes.

Another thing I did on my Kobo is to hide the page numbers, seeing that big 980 pages to go is pretty discouraging, what I did instead is opt for time until finish book and time until finish chapter. Even if I see that I still have nine hours left until I finish the book, I only have twenty minutes for this chapter. After one chapter is done, I only have nineteen minutes with this one, small steps, big gains.

I usually read more technical stuff, but lately I started reading fiction more.
At first I was reluctant to read more books at the same time but now I find it liberating. If I'm to tired for a hard one, let's read something easy, keep the flow going, when I'm bored, switch to the hard one and so one.

On the Kobo I have a reading timer, I usually set it to thirty minutes and try not to interrupt my reading in this interval, no bathroom, no phone checking, just read, after those thirty minutes I might read more or do something else, I'm free, I did my thirty minutes.

Ok, now I'm reading, what about comprehension and understanding?
Here I'm planning a short series of book reviews. By forcing myself to review books I have to be more invested in them, I have to explain some concepts, I have to sumarize parts of the book. 

This is getting to long and I'm loosing focus, I might make this article shorter, I want to keep my promise of finishing stuff no matter what, if I don't finish this, then this will be the final version.


*See you space cowboy!*
