#+STARTUP: showall
#+OPTIONS: toc:nil -:nil
---
layout: post
title: Berlin - Lost and found
comments: true
categories: jrnl
---

Every place I visit bears a predominant feeling. Berlin is a special one, it carries two!

---

#+CAPTION: 2 in 1
#+NAME:   2 in 1
https://i.imgur.com/1mVUoM5.jpg


* Adrift
  
  #+BEGIN_QUOTE
  If one does not know to which port one is sailing, no wind is favorable. - Lucius Annaeus Seneca
  #+END_QUOTE
  
February of this year I was violently pulled out from one life and cast into another. In a split second, I went from something that I understand to something that make's no sense. Without a goal, without a plan, I was adrift, completely lost!

Today we are spoiled by GPS, digital maps, travel guides, and restaurant recommendations. Everything is easy, convenient, clear, but what we gain in comfort, we lose in skill. Inevitably we will get misplaced, but this time, without any capacity to get back!

Berlin was an experiment: no "must-sees", no "must-tries", no travel guides, no plan. Get there, get lost, but find the fucking way back! Feast on being aimless, dominate it, and move on.

Armed with a paper map, I started my journey to discover the capital, see things, learn something. I got lost constantly, but I always found the way. I was an explorer, everything that I found, big or small, I FUCKING FOUND IT, it was my discovery, I felt pride. And I found a lot! People, churches, cemeteries, the Berlin wall that initially I mistook for a construction site, found parks, found food, helped an old lady, was bitten by a dog, heard colours, got drunk, hugged a lady!

But traveling is not enough...

* Alone
#+BEGIN_QUOTE
" The things you’re running away from are with you all the time...
If you really want to escape the things that harass you, what you’re needing is not to be in a different place but to be a different person. - Lucius Annaeus Seneca"
#+END_QUOTE

Just like a wound that needs cleaning before a suture, so a man must fall in ruin before he can rebuild. Demolishing yourself is so much easier when you are alone or surrounded by strangers than in the comfort of your family or friends. 

Being alone also grants to the liberty of becoming anybody you ever dreamed of, without the luggage, without silly mistakes that some people never seem to forget or even worse, never forgive. Starting over is such a luxury nowadays.

By being alone you have no one to fall back to, ask for confirmation, complain, get angry or blame. You do you, and nothing else. By force you must leave your comfort zone, meet new people or accept to be bored. You make your own path, be it good or bad, and follow it, at your own pace. You have more courage, there is no one to suffer but yourself, and you already want to be destroyed, so there's nothing to loose. Everything that you do well, everything that you screw up, it's your fault, but at the same time, your triumph, you share nothing with no one!


What I felt in Berlin was two fold, being lost and loneliness, with a hint of friendship and safeness, but that's a story for another time.

Travel and come back someone else! Hopefully a better one!

*See you space cowboy!*
