#+STARTUP: showall
#+OPTIONS: toc:nil -:nil
---
layout: post
title: WTF is Nim and why it might help you
tags: nim python
---

No programming language is worth learning if it doesn't teach you something new, something useful, makes you better at what you do. Maybe Nim can do that for you, read bellow to find out if so.

---

#+CAPTION: Image credits to www.martianpictures.com
#+NAME:   turtle www.martianpictures.com
http://i.imgur.com/C8n4pHN.jpg

#+TOC: headlines

** Introduction
Nim is a fun language that I started to play with. Reminds me of the same joy I felt about python when I started. In these few line I will tell more about the use cases you can start using Nim in your project without giving up to your favorite tool or language. Will start with a quick sales pitch, move to a demo to better show what I am talking abount and then if you are still interested will move to a more in depth analysis of the language.
** Nim what? (short version)
*** Elevator pitch
Nim (formerly known as "Nimrod") is a statically typed, imperative programming language that tries to give the programmer ultimate power without compromises on runtime efficiency. This means it focuses on compile-time mechanisms in all their various forms.

Beneath a nice infix/indentation based syntax with a powerful (AST based, hygienic) macro system lies a semantic model that supports a soft realtime GC on thread local heaps. Asynchronous message passing is used between threads, so no "stop the world" mechanism is necessary. An unsafe shared memory heap is also provided for the increased efficiency that results from that model.
*** Performance
*** Interoperability
*** Distribution
*** Extensibility
** What's in it for me
** Nim what? (long version)
** Tell me more (I'm interested)
